spring.application.name=game-library

# Ativa o console do H2
spring.h2.console.enabled=true

# Define o caminho para acessar (o padrão já é /h2-console, mas é bom garantir)
spring.h2.console.path=/h2-console

# Configurações do banco de dados em memória
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=