name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: # O 'steps' fica dentro de 'build'
      - name: Baixando o código do repositórios 📂
        uses: actions/checkout@v4

      - name: Instalando o Java JDK ☕
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Executar Testes com Maven 🚀
        run: chmod +x mvnw && ./mvnw clean test